# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: peter wiebe
email: pjwiebe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enjoying the journey, not worrying about the destination. A website dedicated to all the things I have learned and continue to learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: peterjacob
github_username:  peterwiebe

# Build settings
markdown: kramdown
